version: "3.8"

services:
  kener-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "305:3000"
    volumes:
      - /volumes/kerner:/app/static/kerner
    env_file:
      - .env
