- name: 42.mk
  description: Base 42's main site
  tag: "base-42"
  image: "/base42.jpeg"
  api:
    method: GET
    url: https://www.42.mk/
- name: Drug Registry API
  description: The API for the Macedonian drug registry
  tag: "drug-registry"
  image: "/base42.jpeg"
  api:
    method: GET
    url: https://www.42.mk/