name: Build and Push Docker Image

on:
  push:
    branches:
      - 42dotmk

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Docker Image
      run: |
        SHORT_COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
        docker build -t ghcr.io/42dotmk/kener:latest .
        docker tag ghcr.io/42dotmk/kener:latest ghcr.io/42dotmk/kener:$SHORT_COMMIT_HASH
        docker push ghcr.io/42dotmk/kener:latest
        docker push ghcr.io/42dotmk/kener:$SHORT_COMMIT_HASH
